#!/bin/bash
# open-pr.sh — Agent 调用: CP3 完成后触发 PR 创建
# 用法: ./scripts/open-pr.sh [branch]
#
# 触发时机: Agent 完成 CP3 (verify) 后调用
# 依赖: gh CLI (需先 gh auth login)
#
# Autonomy 行为:
#   L1-L3: 仅生成 PR 草稿，人工确认
#   L4:    自动打开 PR，等待人工 merge
#   L5+:   自动打开 PR，CI 通过后自动 merge

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GH_TOKEN="${GH_TOKEN:-$GITHUB_TOKEN}"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
success(){ echo -e "${GREEN}[OK]${NC}    $1"; }

# ── Usage ─────────────────────────────────────────────────────────────────────
usage() {
  cat << EOF
Usage: $0 [options]

Options:
  -b, --branch <name>   Source branch (default: current branch)
  -t, --target <name>   Target branch (default: main)
  -m, --message <msg>   PR body / commit message
  -d, --draft           Create as draft PR
  -l, --level <1-9>     Override autonomy level
  -h, --help            Show this help

Autonomy Levels:
  L1-L3  Draft PR only, human confirms
  L4     Open PR, wait for human merge
  L5+    Open PR, auto-merge on CI pass

Examples:
  $0                           # 自动检测当前分支
  $0 -b feature/login          # 指定分支
  $0 -l 5                      # L5 模式 (自动 merge)
EOF
}

# ── Parse Args ───────────────────────────────────────────────────────────────
BRANCH=""
TARGET="main"
DRAFT=false
AUTONOMY_LEVEL=""
PR_MESSAGE=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -b|--branch)   BRANCH="$2";     shift 2 ;;
    -t|--target)   TARGET="$2";     shift 2 ;;
    -m|--message)  PR_MESSAGE="$2"; shift 2 ;;
    -d|--draft)    DRAFT=true;      shift   ;;
    -l|--level)    AUTONOMY_LEVEL="$2"; shift 2 ;;
    -h|--help)     usage; exit 0 ;;
    *)             error "Unknown option: $1"; usage; exit 1 ;;
  esac
done

# ── Pre-checks ────────────────────────────────────────────────────────────────
# 1. gh CLI
if ! command -v gh &>/dev/null; then
  error "gh CLI not found. Install: https://cli.github.com/"
  exit 1
fi

# 2. Auth
if ! gh auth status &>/dev/null; then
  error "Not logged in to gh. Run: gh auth login"
  exit 1
fi

# 3. Git repo
cd "$PROJECT_ROOT"
if ! git rev-parse --git-dir &>/dev/null; then
  error "Not a git repository: $PROJECT_ROOT"
  exit 1
fi

# ── Resolve branch ───────────────────────────────────────────────────────────
if [ -z "$BRANCH" ]; then
  BRANCH=$(git branch --show-current)
fi
if [ -z "$BRANCH" ]; then
  error "Cannot determine current branch. Use -b <name>"
  exit 1
fi

info "Branch: $BRANCH → $TARGET"

# ── Check CP3 state ───────────────────────────────────────────────────────────
check_cp3() {
  local state_file="$PROJECT_ROOT/harness/feedback/state/state.json"
  if [ ! -f "$state_file" ]; then
    warn "No harness state found at $state_file"
    return 0  # Not a hard error
  fi

  local cp3_status
  cp3_status=$(python3 -c "
import json, sys
state = json.load(open('$state_file'))
cp3 = state.get('checkpoints', {}).get('CP3', {})
print(cp3.get('status', 'unknown'))
" 2>/dev/null || echo "unknown")

  if [ "$cp3_status" != "completed" ]; then
    warn "CP3 status is '$cp3_status', expected 'completed'"
    warn "Continuing anyway (CP3 check is advisory)"
  else
    success "CP3 verified: completed"
  fi
}

# ── Determine autonomy level ──────────────────────────────────────────────────
get_autonomy_level() {
  if [ -n "$AUTONOMY_LEVEL" ]; then
    echo "$AUTONOMY_LEVEL"
    return
  fi

  local state_file="$PROJECT_ROOT/harness/feedback/state/state.json"
  if [ -f "$state_file" ]; then
    python3 -c "
import json, sys
state = json.load(open('$state_file'))
level = state.get('autonomy', {}).get('level', 4)
print(level)
" 2>/dev/null && return
  fi

  echo "4"  # Default to L4
}

# ── Read recent commit ────────────────────────────────────────────────────────
get_pr_title() {
  if [ -n "$PR_MESSAGE" ]; then
    echo "$PR_MESSAGE"
    return
  fi
  git log --oneline -1 --format="%s" 2>/dev/null || echo "Update from agent"
}

# ── Create PR ─────────────────────────────────────────────────────────────────
create_pr() {
  local title
  local draft_flag=""
  title=$(get_pr_title)

  [ "$DRAFT" = true ] && draft_flag="--draft"

  info "Creating PR: '$title'"
  info "Source: $BRANCH → Target: $TARGET"

  local AL
  AL=$(get_autonomy_level)
  info "Autonomy Level: L$AL"

  # Generate PR body
  local pr_body
  pr_body=$(cat << EOF
## Agent Pull Request

**Autonomy Level:** L$AL
**CP3 Status:** ✅ Completed (verified by open-pr.sh)
**Branch:** \`$BRANCH\` → \`$TARGET\`

---
_Auto-generated by harness-monorepo PR workflow_
EOF
)

  # Create the PR
  local pr_url
  pr_url=$(gh pr create \
    --title "$title" \
    --body "$pr_body" \
    --base "$TARGET" \
    --head "$BRANCH" \
    $draft_flag \
    --repo "$(git remote get-url origin | sed 's/.*github.com[/:]//' | sed 's/.git$//')" \
    2>&1)
  local exit_code=$?

  if [ $exit_code -ne 0 ]; then
    error "Failed to create PR: $pr_url"
    exit 1
  fi

  success "PR created: $pr_url"

  # Label the PR
  gh pr edit "$pr_url" --add-label "harness,auto-pr,cp3-complete" 2>/dev/null || true

  echo ""
  echo "========================================"
  echo "  PR URL: $pr_url"
  echo "  Autonomy Level: L$AL"
  if [ "$AL" -ge 5 ]; then
    echo "  Auto-merge: Will trigger when CI passes"
  elif [ "$AL" -ge 4 ]; then
    echo "  Auto-merge: Disabled (L$AL) — merge manually"
  else
    echo "  Draft PR — please review and publish"
  fi
  echo "========================================"

  # If L5+, also trigger the repository_dispatch for CI workflow
  if [ "$AL" -ge 5 ]; then
    info "Triggering CI via repository_dispatch..."
    REPO=$(git remote get-url origin | sed 's/.*github.com[/:]//' | sed 's/.git$//')
    OWNER=$(echo "$REPO" | cut -d/ -f1)
    REPO_NAME=$(echo "$REPO" | cut -d/ -f2)
    gh api repos/"$OWNER"/"$REPO_NAME"/dispatches \
      --field event_type=cp3-complete \
      --field client_payload[pr_url]="$pr_url" \
      --field client_payload[autonomy_level]="$AL" \
      2>/dev/null || true
  fi
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  info "=== Harness PR Workflow ==="
  check_cp3
  create_pr
}

main
