#!/usr/bin/env python3
"""
Harness Generator — Generate project structures from templates.
"""

import argparse
import os
import sys
import shutil
from datetime import datetime
from pathlib import Path

TEMPLATES = {
    "basic": {
        "description": "Basic Harness project structure",
        "files": {
            "harness/base/constraints.md": "# Harness Constraints\n\n## Core Principles\n\n- Default Deny\n- Sandbox Inside = Fully Trusted\n- Checkpoint Before Action\n",
            "harness/base/state.json": '''{
  "_schema": "harness-v2",
  "version": "1.0.0",
  "type": "generic",
  "platform": "auto",
  "lastUpdated": "%s",
  "currentTask": null,
  "taskStatus": "idle",
  "checkpoints": {"CP0": "pending", "CP1": "pending", "CP2": "pending", "CP3": "pending"},
  "gates": {"init": "pending", "plan": "pending", "exec": "pending", "verify": "pending"},
  "metrics": {"tasksCompleted": 0, "tasksBlocked": 0, "averageTaskDuration": 0}
}''',
            "harness/feedback/state/state.json": '{"_schema": "harness-v2"}',
            "skills/README.md": "# Skills\n\nPlace skill definitions here.\n",
            "README.md": "# Harness Project\n\nGenerated by harness-generator.\n",
        },
    },
    "electron": {
        "description": "Electron + Tauri agent harness",
        "files": {
            "harness/base/constraints.md": "# Electron Harness Constraints\n\n## Core Principles\n\n- Default Deny\n- Sandbox Inside = Fully Trusted\n- Checkpoint Before Action\n- Metric Everything\n\n## Allowed Paths\n\n- ~/workspace/**\n- ~/projects/**\n- /tmp/harness/**\n\n## Blocked Paths\n\n- ~/.ssh/**\n- /etc/**\n- ~/.aws/**\n\n## Electron-Specific\n\n- Use `npm run build` for production builds\n- Use `npm run dev` for development\n- MCP packages must be installed in isolation\n",
            "harness/base/state.json": '''{
  "_schema": "harness-v2",
  "version": "1.0.0",
  "type": "electron",
  "platform": "electron",
  "lastUpdated": "%s",
  "currentTask": null,
  "taskStatus": "idle",
  "checkpoints": {"CP0": "pending", "CP1": "pending", "CP2": "pending", "CP3": "pending"},
  "gates": {"init": "pending", "plan": "pending", "exec": "pending", "verify": "pending", "test": "pending", "build": "pending"},
  "metrics": {"tasksCompleted": 0, "tasksBlocked": 0, "averageTaskDuration": 0, "mcpPackagesInstalled": 0}
}''',
            "harness/feedback/state/state.json": '{"_schema": "harness-v2"}',
            "skills/README.md": "# Skills\n\nPlace skill definitions here.\n",
            "scripts/dev.sh": "#!/bin/bash\nnpm run dev\n",
            "scripts/build.sh": "#!/bin/bash\nnpm run build\n",
            ".gitignore": "node_modules/\ndist/\nout/\n*.log\n",
            "README.md": "# Electron Harness Project\n\nGenerated by harness-generator.\n",
        },
    },
    "agent": {
        "description": "AI agent project with ACP protocol",
        "files": {
            "harness/base/constraints.md": "# Agent Harness Constraints\n\n## Core Principles\n\n- Default Deny\n- Sandbox Inside = Fully Trusted\n- Checkpoint Before Action\n- Metric Everything\n\n## Allowed Paths\n\n- ~/workspace/**\n- ~/projects/**\n\n## Blocked Paths\n\n- ~/.ssh/**\n- /etc/**\n- ~/.aws/**\n\n## Autonomy\n\n- Default: L2 (Executor)\n- Approval required for: delete, network_request\n- Auto-merge on CI: false\n",
            "harness/base/state.json": '''{
  "_schema": "harness-v2",
  "version": "1.0.0",
  "type": "agent",
  "platform": "universal",
  "lastUpdated": "%s",
  "currentTask": null,
  "taskStatus": "idle",
  "autonomy": {"level": 2, "requireApprovalFor": ["delete", "network_request"], "autoMergeOnCI": false},
  "checkpoints": {"CP0": "pending", "CP1": "pending", "CP2": "pending", "CP3": "pending", "CP4": "pending"},
  "gates": {"init": "pending", "plan": "pending", "exec": "pending", "verify": "pending", "complete": "pending"},
  "metrics": {"tasksCompleted": 0, "tasksBlocked": 0, "averageTaskDuration": 0, "selfCorrections": 0, "humanInterventions": 0}
}''',
            "harness/feedback/state/state.json": '{"_schema": "harness-v2"}',
            "skills/README.md": "# Skills\n\nPlace skill definitions here.\n",
            "README.md": "# Agent Harness Project\n\nGenerated by harness-generator.\n",
        },
    },
}


def scaffold(output_dir: Path, template: str, force: bool = False):
    if output_dir.exists() and any(output_dir.iterdir()):
        if not force:
            print(f"[ERROR] Directory {output_dir} is not empty. Use --force to overwrite.")
            return False

    if template not in TEMPLATES:
        print(f"[ERROR] Unknown template: {template}")
        print(f"Available: {', '.join(TEMPLATES.keys())}")
        return False

    now = datetime.now().isoformat()
    files = TEMPLATES[template]["files"]

    for path_str, content in files.items():
        full_path = output_dir / path_str
        full_path.parent.mkdir(parents=True, exist_ok=True)
        filled = content % now if "%s" in content else content
        full_path.write_text(filled)
        print(f"  + {path_str}")

    if os.name != "nt":
        for root, dirs, filenames in os.walk(output_dir / "scripts"):
            for fn in filenames:
                p = Path(root) / fn
                p.chmod(0o755)

    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Harness Generator")
    parser.add_argument(
        "--template", "-t",
        choices=list(TEMPLATES.keys()),
        default="basic",
        help="Project template",
    )
    parser.add_argument(
        "--output", "-o",
        default="./harness-project",
        help="Output directory",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing directory",
    )
    parser.add_argument(
        "--list", "-l",
        action="store_true",
        help="List available templates",
    )

    args = parser.parse_args()

    if args.list:
        print("\nAvailable templates:\n")
        for name, tpl in TEMPLATES.items():
            print(f"  {name:12} — {tpl['description']}")
        print()
        return 0

    output = Path(args.output).expanduser().resolve()

    print(f"\nGenerating '{args.template}' harness at {output}/\n")
    if scaffold(output, args.template, args.force):
        print(f"\n[OK] Scaffold complete at {output}/")
        print(f"  Template: {args.template}")
        print(f"  Files: {len(TEMPLATES[args.template]['files'])}")
    else:
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())